apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    repoURL: https://github.com/sounakpatra/argocd-update.git
    targetRevision: HEAD
    path: update
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

